apiVersion: v1
kind: PersistentVolume
metadata:
  name: cf-2g-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-0d872f5527171ee4c"
