apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-3g-b1"
spec:
  capacity:
    storage: "3Gi"
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: "vol-0362753d94ee15939"
